/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PrivateLayoutRouteImport } from './routes/_privateLayout'
import { Route as DefaultLayoutRouteImport } from './routes/_defaultLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as AdminLayoutRouteImport } from './routes/_adminLayout'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_defaultLayout/index'
import { Route as PrivateLayoutSavedPostsRouteImport } from './routes/_privateLayout/saved-posts'
import { Route as PrivateLayoutLikedPostsRouteImport } from './routes/_privateLayout/liked-posts'
import { Route as PrivateLayoutExploreRouteImport } from './routes/_privateLayout/explore'
import { Route as PrivateLayoutCreatePostRouteImport } from './routes/_privateLayout/create-post'
import { Route as PrivateLayoutCommunityRouteImport } from './routes/_privateLayout/community'
import { Route as PrivateLayoutAllUsersRouteImport } from './routes/_privateLayout/all-users'
import { Route as DefaultLayoutGalleryRouteImport } from './routes/_defaultLayout/gallery'
import { Route as DefaultLayoutEventsRouteImport } from './routes/_defaultLayout/events'
import { Route as DefaultLayoutAboutUsRouteImport } from './routes/_defaultLayout/about-us'
import { Route as AuthLayoutSignupRouteImport } from './routes/_authLayout/signup'
import { Route as AuthLayoutResetPasswordRouteImport } from './routes/_authLayout/reset-password'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as AuthLayoutForgotPasswordRouteImport } from './routes/_authLayout/forgot-password'
import { Route as PrivateLayoutNewsletterIndexRouteImport } from './routes/_privateLayout/newsletter/index'
import { Route as PrivateLayoutMessagesIndexRouteImport } from './routes/_privateLayout/messages/index'
import { Route as AdminLayoutAdminIndexRouteImport } from './routes/_adminLayout/admin/index'
import { Route as PrivateLayoutUUserIdRouteImport } from './routes/_privateLayout/u/$userId'
import { Route as PrivateLayoutPostsPostIdRouteImport } from './routes/_privateLayout/posts/$postId'
import { Route as PrivateLayoutNewsletterNewsIdRouteImport } from './routes/_privateLayout/newsletter/$newsId'
import { Route as PrivateLayoutMessagesUserIdRouteImport } from './routes/_privateLayout/messages/$userId'
import { Route as PrivateLayoutEditPostPostIdRouteImport } from './routes/_privateLayout/edit-post/$postId'
import { Route as AdminLayoutAdminEventsRouteImport } from './routes/_adminLayout/admin/events'
import { Route as AdminLayoutAdminAboutUsRouteImport } from './routes/_adminLayout/admin/about-us'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_privateLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: '/_defaultLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const PrivateLayoutSavedPostsRoute = PrivateLayoutSavedPostsRouteImport.update({
  id: '/saved-posts',
  path: '/saved-posts',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutLikedPostsRoute = PrivateLayoutLikedPostsRouteImport.update({
  id: '/liked-posts',
  path: '/liked-posts',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutExploreRoute = PrivateLayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCreatePostRoute = PrivateLayoutCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCommunityRoute = PrivateLayoutCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutAllUsersRoute = PrivateLayoutAllUsersRouteImport.update({
  id: '/all-users',
  path: '/all-users',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const DefaultLayoutGalleryRoute = DefaultLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutEventsRoute = DefaultLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutAboutUsRoute = DefaultLayoutAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const AuthLayoutSignupRoute = AuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutResetPasswordRoute = AuthLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutForgotPasswordRoute =
  AuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const PrivateLayoutNewsletterIndexRoute =
  PrivateLayoutNewsletterIndexRouteImport.update({
    id: '/newsletter/',
    path: '/newsletter/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutMessagesIndexRoute =
  PrivateLayoutMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const AdminLayoutAdminIndexRoute = AdminLayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PrivateLayoutUUserIdRoute = PrivateLayoutUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutPostsPostIdRoute =
  PrivateLayoutPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutNewsletterNewsIdRoute =
  PrivateLayoutNewsletterNewsIdRouteImport.update({
    id: '/newsletter/$newsId',
    path: '/newsletter/$newsId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutMessagesUserIdRoute =
  PrivateLayoutMessagesUserIdRouteImport.update({
    id: '/messages/$userId',
    path: '/messages/$userId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutEditPostPostIdRoute =
  PrivateLayoutEditPostPostIdRouteImport.update({
    id: '/edit-post/$postId',
    path: '/edit-post/$postId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const AdminLayoutAdminEventsRoute = AdminLayoutAdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAdminAboutUsRoute = AdminLayoutAdminAboutUsRouteImport.update({
  id: '/admin/about-us',
  path: '/admin/about-us',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/about-us': typeof DefaultLayoutAboutUsRoute
  '/events': typeof DefaultLayoutEventsRoute
  '/gallery': typeof DefaultLayoutGalleryRoute
  '/all-users': typeof PrivateLayoutAllUsersRoute
  '/community': typeof PrivateLayoutCommunityRoute
  '/create-post': typeof PrivateLayoutCreatePostRoute
  '/explore': typeof PrivateLayoutExploreRoute
  '/liked-posts': typeof PrivateLayoutLikedPostsRoute
  '/saved-posts': typeof PrivateLayoutSavedPostsRoute
  '/admin/about-us': typeof AdminLayoutAdminAboutUsRoute
  '/admin/events': typeof AdminLayoutAdminEventsRoute
  '/edit-post/$postId': typeof PrivateLayoutEditPostPostIdRoute
  '/messages/$userId': typeof PrivateLayoutMessagesUserIdRoute
  '/newsletter/$newsId': typeof PrivateLayoutNewsletterNewsIdRoute
  '/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
  '/u/$userId': typeof PrivateLayoutUUserIdRoute
  '/admin/': typeof AdminLayoutAdminIndexRoute
  '/messages/': typeof PrivateLayoutMessagesIndexRoute
  '/newsletter/': typeof PrivateLayoutNewsletterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultLayoutIndexRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/about-us': typeof DefaultLayoutAboutUsRoute
  '/events': typeof DefaultLayoutEventsRoute
  '/gallery': typeof DefaultLayoutGalleryRoute
  '/all-users': typeof PrivateLayoutAllUsersRoute
  '/community': typeof PrivateLayoutCommunityRoute
  '/create-post': typeof PrivateLayoutCreatePostRoute
  '/explore': typeof PrivateLayoutExploreRoute
  '/liked-posts': typeof PrivateLayoutLikedPostsRoute
  '/saved-posts': typeof PrivateLayoutSavedPostsRoute
  '/admin/about-us': typeof AdminLayoutAdminAboutUsRoute
  '/admin/events': typeof AdminLayoutAdminEventsRoute
  '/edit-post/$postId': typeof PrivateLayoutEditPostPostIdRoute
  '/messages/$userId': typeof PrivateLayoutMessagesUserIdRoute
  '/newsletter/$newsId': typeof PrivateLayoutNewsletterNewsIdRoute
  '/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
  '/u/$userId': typeof PrivateLayoutUUserIdRoute
  '/admin': typeof AdminLayoutAdminIndexRoute
  '/messages': typeof PrivateLayoutMessagesIndexRoute
  '/newsletter': typeof PrivateLayoutNewsletterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_defaultLayout': typeof DefaultLayoutRouteWithChildren
  '/_privateLayout': typeof PrivateLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/_authLayout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/reset-password': typeof AuthLayoutResetPasswordRoute
  '/_authLayout/signup': typeof AuthLayoutSignupRoute
  '/_defaultLayout/about-us': typeof DefaultLayoutAboutUsRoute
  '/_defaultLayout/events': typeof DefaultLayoutEventsRoute
  '/_defaultLayout/gallery': typeof DefaultLayoutGalleryRoute
  '/_privateLayout/all-users': typeof PrivateLayoutAllUsersRoute
  '/_privateLayout/community': typeof PrivateLayoutCommunityRoute
  '/_privateLayout/create-post': typeof PrivateLayoutCreatePostRoute
  '/_privateLayout/explore': typeof PrivateLayoutExploreRoute
  '/_privateLayout/liked-posts': typeof PrivateLayoutLikedPostsRoute
  '/_privateLayout/saved-posts': typeof PrivateLayoutSavedPostsRoute
  '/_defaultLayout/': typeof DefaultLayoutIndexRoute
  '/_adminLayout/admin/about-us': typeof AdminLayoutAdminAboutUsRoute
  '/_adminLayout/admin/events': typeof AdminLayoutAdminEventsRoute
  '/_privateLayout/edit-post/$postId': typeof PrivateLayoutEditPostPostIdRoute
  '/_privateLayout/messages/$userId': typeof PrivateLayoutMessagesUserIdRoute
  '/_privateLayout/newsletter/$newsId': typeof PrivateLayoutNewsletterNewsIdRoute
  '/_privateLayout/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
  '/_privateLayout/u/$userId': typeof PrivateLayoutUUserIdRoute
  '/_adminLayout/admin/': typeof AdminLayoutAdminIndexRoute
  '/_privateLayout/messages/': typeof PrivateLayoutMessagesIndexRoute
  '/_privateLayout/newsletter/': typeof PrivateLayoutNewsletterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/about-us'
    | '/events'
    | '/gallery'
    | '/all-users'
    | '/community'
    | '/create-post'
    | '/explore'
    | '/liked-posts'
    | '/saved-posts'
    | '/admin/about-us'
    | '/admin/events'
    | '/edit-post/$postId'
    | '/messages/$userId'
    | '/newsletter/$newsId'
    | '/posts/$postId'
    | '/u/$userId'
    | '/admin/'
    | '/messages/'
    | '/newsletter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/about-us'
    | '/events'
    | '/gallery'
    | '/all-users'
    | '/community'
    | '/create-post'
    | '/explore'
    | '/liked-posts'
    | '/saved-posts'
    | '/admin/about-us'
    | '/admin/events'
    | '/edit-post/$postId'
    | '/messages/$userId'
    | '/newsletter/$newsId'
    | '/posts/$postId'
    | '/u/$userId'
    | '/admin'
    | '/messages'
    | '/newsletter'
  id:
    | '__root__'
    | '/_adminLayout'
    | '/_authLayout'
    | '/_defaultLayout'
    | '/_privateLayout'
    | '/test'
    | '/_authLayout/forgot-password'
    | '/_authLayout/login'
    | '/_authLayout/reset-password'
    | '/_authLayout/signup'
    | '/_defaultLayout/about-us'
    | '/_defaultLayout/events'
    | '/_defaultLayout/gallery'
    | '/_privateLayout/all-users'
    | '/_privateLayout/community'
    | '/_privateLayout/create-post'
    | '/_privateLayout/explore'
    | '/_privateLayout/liked-posts'
    | '/_privateLayout/saved-posts'
    | '/_defaultLayout/'
    | '/_adminLayout/admin/about-us'
    | '/_adminLayout/admin/events'
    | '/_privateLayout/edit-post/$postId'
    | '/_privateLayout/messages/$userId'
    | '/_privateLayout/newsletter/$newsId'
    | '/_privateLayout/posts/$postId'
    | '/_privateLayout/u/$userId'
    | '/_adminLayout/admin/'
    | '/_privateLayout/messages/'
    | '/_privateLayout/newsletter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout': {
      id: '/_privateLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout': {
      id: '/_defaultLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/': {
      id: '/_defaultLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_privateLayout/saved-posts': {
      id: '/_privateLayout/saved-posts'
      path: '/saved-posts'
      fullPath: '/saved-posts'
      preLoaderRoute: typeof PrivateLayoutSavedPostsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/liked-posts': {
      id: '/_privateLayout/liked-posts'
      path: '/liked-posts'
      fullPath: '/liked-posts'
      preLoaderRoute: typeof PrivateLayoutLikedPostsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/explore': {
      id: '/_privateLayout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof PrivateLayoutExploreRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/create-post': {
      id: '/_privateLayout/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof PrivateLayoutCreatePostRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/community': {
      id: '/_privateLayout/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof PrivateLayoutCommunityRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/all-users': {
      id: '/_privateLayout/all-users'
      path: '/all-users'
      fullPath: '/all-users'
      preLoaderRoute: typeof PrivateLayoutAllUsersRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_defaultLayout/gallery': {
      id: '/_defaultLayout/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof DefaultLayoutGalleryRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/events': {
      id: '/_defaultLayout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DefaultLayoutEventsRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/about-us': {
      id: '/_defaultLayout/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof DefaultLayoutAboutUsRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/reset-password': {
      id: '/_authLayout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/forgot-password': {
      id: '/_authLayout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_privateLayout/newsletter/': {
      id: '/_privateLayout/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof PrivateLayoutNewsletterIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/messages/': {
      id: '/_privateLayout/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof PrivateLayoutMessagesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_adminLayout/admin/': {
      id: '/_adminLayout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutAdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_privateLayout/u/$userId': {
      id: '/_privateLayout/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof PrivateLayoutUUserIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/posts/$postId': {
      id: '/_privateLayout/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PrivateLayoutPostsPostIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/newsletter/$newsId': {
      id: '/_privateLayout/newsletter/$newsId'
      path: '/newsletter/$newsId'
      fullPath: '/newsletter/$newsId'
      preLoaderRoute: typeof PrivateLayoutNewsletterNewsIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/messages/$userId': {
      id: '/_privateLayout/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof PrivateLayoutMessagesUserIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/edit-post/$postId': {
      id: '/_privateLayout/edit-post/$postId'
      path: '/edit-post/$postId'
      fullPath: '/edit-post/$postId'
      preLoaderRoute: typeof PrivateLayoutEditPostPostIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_adminLayout/admin/events': {
      id: '/_adminLayout/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutAdminEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_adminLayout/admin/about-us': {
      id: '/_adminLayout/admin/about-us'
      path: '/admin/about-us'
      fullPath: '/admin/about-us'
      preLoaderRoute: typeof AdminLayoutAdminAboutUsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAdminAboutUsRoute: typeof AdminLayoutAdminAboutUsRoute
  AdminLayoutAdminEventsRoute: typeof AdminLayoutAdminEventsRoute
  AdminLayoutAdminIndexRoute: typeof AdminLayoutAdminIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminAboutUsRoute: AdminLayoutAdminAboutUsRoute,
  AdminLayoutAdminEventsRoute: AdminLayoutAdminEventsRoute,
  AdminLayoutAdminIndexRoute: AdminLayoutAdminIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutResetPasswordRoute: typeof AuthLayoutResetPasswordRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutResetPasswordRoute: AuthLayoutResetPasswordRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DefaultLayoutRouteChildren {
  DefaultLayoutAboutUsRoute: typeof DefaultLayoutAboutUsRoute
  DefaultLayoutEventsRoute: typeof DefaultLayoutEventsRoute
  DefaultLayoutGalleryRoute: typeof DefaultLayoutGalleryRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutAboutUsRoute: DefaultLayoutAboutUsRoute,
  DefaultLayoutEventsRoute: DefaultLayoutEventsRoute,
  DefaultLayoutGalleryRoute: DefaultLayoutGalleryRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

interface PrivateLayoutRouteChildren {
  PrivateLayoutAllUsersRoute: typeof PrivateLayoutAllUsersRoute
  PrivateLayoutCommunityRoute: typeof PrivateLayoutCommunityRoute
  PrivateLayoutCreatePostRoute: typeof PrivateLayoutCreatePostRoute
  PrivateLayoutExploreRoute: typeof PrivateLayoutExploreRoute
  PrivateLayoutLikedPostsRoute: typeof PrivateLayoutLikedPostsRoute
  PrivateLayoutSavedPostsRoute: typeof PrivateLayoutSavedPostsRoute
  PrivateLayoutEditPostPostIdRoute: typeof PrivateLayoutEditPostPostIdRoute
  PrivateLayoutMessagesUserIdRoute: typeof PrivateLayoutMessagesUserIdRoute
  PrivateLayoutNewsletterNewsIdRoute: typeof PrivateLayoutNewsletterNewsIdRoute
  PrivateLayoutPostsPostIdRoute: typeof PrivateLayoutPostsPostIdRoute
  PrivateLayoutUUserIdRoute: typeof PrivateLayoutUUserIdRoute
  PrivateLayoutMessagesIndexRoute: typeof PrivateLayoutMessagesIndexRoute
  PrivateLayoutNewsletterIndexRoute: typeof PrivateLayoutNewsletterIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutAllUsersRoute: PrivateLayoutAllUsersRoute,
  PrivateLayoutCommunityRoute: PrivateLayoutCommunityRoute,
  PrivateLayoutCreatePostRoute: PrivateLayoutCreatePostRoute,
  PrivateLayoutExploreRoute: PrivateLayoutExploreRoute,
  PrivateLayoutLikedPostsRoute: PrivateLayoutLikedPostsRoute,
  PrivateLayoutSavedPostsRoute: PrivateLayoutSavedPostsRoute,
  PrivateLayoutEditPostPostIdRoute: PrivateLayoutEditPostPostIdRoute,
  PrivateLayoutMessagesUserIdRoute: PrivateLayoutMessagesUserIdRoute,
  PrivateLayoutNewsletterNewsIdRoute: PrivateLayoutNewsletterNewsIdRoute,
  PrivateLayoutPostsPostIdRoute: PrivateLayoutPostsPostIdRoute,
  PrivateLayoutUUserIdRoute: PrivateLayoutUUserIdRoute,
  PrivateLayoutMessagesIndexRoute: PrivateLayoutMessagesIndexRoute,
  PrivateLayoutNewsletterIndexRoute: PrivateLayoutNewsletterIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
