/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PrivateLayoutRouteImport } from './routes/_privateLayout'
import { Route as DefaultLayoutRouteImport } from './routes/_defaultLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_defaultLayout/index'
import { Route as PrivateLayoutExploreRouteImport } from './routes/_privateLayout/explore'
import { Route as PrivateLayoutCommunityRouteImport } from './routes/_privateLayout/community'
import { Route as DefaultLayoutGalleryRouteImport } from './routes/_defaultLayout/gallery'
import { Route as DefaultLayoutEventsRouteImport } from './routes/_defaultLayout/events'
import { Route as DefaultLayoutAboutUsRouteImport } from './routes/_defaultLayout/about-us'
import { Route as AuthLayoutSignupRouteImport } from './routes/_authLayout/signup'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as PrivateLayoutPostsPostIdRouteImport } from './routes/_privateLayout/posts/$postId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_privateLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: '/_defaultLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const PrivateLayoutExploreRoute = PrivateLayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCommunityRoute = PrivateLayoutCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const DefaultLayoutGalleryRoute = DefaultLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutEventsRoute = DefaultLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutAboutUsRoute = DefaultLayoutAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const AuthLayoutSignupRoute = AuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const PrivateLayoutPostsPostIdRoute =
  PrivateLayoutPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/test': typeof TestRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/about-us': typeof DefaultLayoutAboutUsRoute
  '/events': typeof DefaultLayoutEventsRoute
  '/gallery': typeof DefaultLayoutGalleryRoute
  '/community': typeof PrivateLayoutCommunityRoute
  '/explore': typeof PrivateLayoutExploreRoute
  '/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultLayoutIndexRoute
  '/test': typeof TestRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/about-us': typeof DefaultLayoutAboutUsRoute
  '/events': typeof DefaultLayoutEventsRoute
  '/gallery': typeof DefaultLayoutGalleryRoute
  '/community': typeof PrivateLayoutCommunityRoute
  '/explore': typeof PrivateLayoutExploreRoute
  '/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_defaultLayout': typeof DefaultLayoutRouteWithChildren
  '/_privateLayout': typeof PrivateLayoutRouteWithChildren
  '/test': typeof TestRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/signup': typeof AuthLayoutSignupRoute
  '/_defaultLayout/about-us': typeof DefaultLayoutAboutUsRoute
  '/_defaultLayout/events': typeof DefaultLayoutEventsRoute
  '/_defaultLayout/gallery': typeof DefaultLayoutGalleryRoute
  '/_privateLayout/community': typeof PrivateLayoutCommunityRoute
  '/_privateLayout/explore': typeof PrivateLayoutExploreRoute
  '/_defaultLayout/': typeof DefaultLayoutIndexRoute
  '/_privateLayout/posts/$postId': typeof PrivateLayoutPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/login'
    | '/signup'
    | '/about-us'
    | '/events'
    | '/gallery'
    | '/community'
    | '/explore'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/login'
    | '/signup'
    | '/about-us'
    | '/events'
    | '/gallery'
    | '/community'
    | '/explore'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_defaultLayout'
    | '/_privateLayout'
    | '/test'
    | '/_authLayout/login'
    | '/_authLayout/signup'
    | '/_defaultLayout/about-us'
    | '/_defaultLayout/events'
    | '/_defaultLayout/gallery'
    | '/_privateLayout/community'
    | '/_privateLayout/explore'
    | '/_defaultLayout/'
    | '/_privateLayout/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout': {
      id: '/_privateLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout': {
      id: '/_defaultLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/': {
      id: '/_defaultLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_privateLayout/explore': {
      id: '/_privateLayout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof PrivateLayoutExploreRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/community': {
      id: '/_privateLayout/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof PrivateLayoutCommunityRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_defaultLayout/gallery': {
      id: '/_defaultLayout/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof DefaultLayoutGalleryRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/events': {
      id: '/_defaultLayout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DefaultLayoutEventsRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/about-us': {
      id: '/_defaultLayout/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof DefaultLayoutAboutUsRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_privateLayout/posts/$postId': {
      id: '/_privateLayout/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PrivateLayoutPostsPostIdRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DefaultLayoutRouteChildren {
  DefaultLayoutAboutUsRoute: typeof DefaultLayoutAboutUsRoute
  DefaultLayoutEventsRoute: typeof DefaultLayoutEventsRoute
  DefaultLayoutGalleryRoute: typeof DefaultLayoutGalleryRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutAboutUsRoute: DefaultLayoutAboutUsRoute,
  DefaultLayoutEventsRoute: DefaultLayoutEventsRoute,
  DefaultLayoutGalleryRoute: DefaultLayoutGalleryRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

interface PrivateLayoutRouteChildren {
  PrivateLayoutCommunityRoute: typeof PrivateLayoutCommunityRoute
  PrivateLayoutExploreRoute: typeof PrivateLayoutExploreRoute
  PrivateLayoutPostsPostIdRoute: typeof PrivateLayoutPostsPostIdRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutCommunityRoute: PrivateLayoutCommunityRoute,
  PrivateLayoutExploreRoute: PrivateLayoutExploreRoute,
  PrivateLayoutPostsPostIdRoute: PrivateLayoutPostsPostIdRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
